[nfs]
172.31.94.16 ansible_ssh_user='ec2-user'

[webservers]
172.31.89.120 ansible_ssh_user='ec2-user'
172.31.94.25 ansible_ssh_user='ec2-user'

[db]
172.31.16.199 ansible_ssh_user='ec2-user' 

[lb]
172.31.82.155 ansible_ssh_user='ubuntu'

