[nfs]
172.31.94.16 ansible_ssh_user='ec2-user'

[webservers]
172.31.92.139 ansible_ssh_user='ec2-user'
172.31.90.208 ansible_ssh_user='ec2-user'

[db]
172.31.16.199 ansible_ssh_user='ubuntu' 

[lb]
172.31.81.128 ansible_ssh_user='ubuntu'
