---
- name: install apache
  become: true
  ansible.builtin.apt:
    name: "apache2"
    state: present

- name: install git
  become: true
  ansible.builtin.apt:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.apt:
    git:
      repo: https://github.com/Tonybesto/tooling.git
      dest: /var/www/html
      clone: yes
      update: yes
      force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent