---
- hosts: all

- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Delete wireshark installation
  import_playbook: ../static-assignments/common-del.yml

- name: webserver
  import_playbook: ../static-assignments/webservers.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
