---
- hosts: all
- name: Include dynamic variables 
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: db
- name: database mysql configuration
  import_playbook: ../static-assignments/mysql.yml

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignments/loadbalancer.yml
  when: load_balancer_is_required 